version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:calroute@db/calroute_db
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: calroute_db
      MYSQL_USER: caluser
      MYSQL_PASSWORD: calroute
      MYSQL_ROOT_PASSWORD: avi1234ben
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: