version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:5000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:calroute@db/calroute_db
      - FLASK_DEBUG=1
      - DB_HOST=db
      - DB_PORT=3306  
      - PYTHONPATH=/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: calroute_db
      MYSQL_USER: caluser
      MYSQL_PASSWORD: calroute
      MYSQL_ROOT_PASSWORD: calroute
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

volumes:
  db_data: