"""added location flexiblity

Revision ID: 14a3758863c9
Revises: 55cbfa630359
Create Date: 2025-05-27 00:05:13.293241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14a3758863c9'
down_revision = '55cbfa630359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_location_flexible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('place_type', sa.String(length=100), nullable=True))

    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('pending', 'completed', 'cancelled'), nullable=True))

    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.drop_column('place_type')
        batch_op.drop_column('is_location_flexible')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
