"""empty message

Revision ID: 1bbccb031710
Revises: 9cb417623045
Create Date: 2025-05-23 03:46:15.474634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bbccb031710'
down_revision = '9cb417623045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transit_mode_options',
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('mode')
    )
    op.create_table('user_favorite_stores',
    sa.Column('pref_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pref_id'], ['user_preferences.pref_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pref_id', 'location_id')
    )
    op.create_table('user_transit_modes',
    sa.Column('pref_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pref_id'], ['user_preferences.pref_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pref_id', 'mode')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_location_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'locations', ['gym_location_id'], ['location_id'], ondelete='SET NULL')
        batch_op.drop_column('travel_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_mode', mysql.ENUM('car', 'bike', 'bus_train', 'walking', 'rideshare'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('gym_location_id')

    op.drop_table('user_transit_modes')
    op.drop_table('user_favorite_stores')
    op.drop_table('transit_mode_options')
    # ### end Alembic commands ###
