"""added flexibility of location

Revision ID: 3f07a1ae24f2
Revises: 9cb417623045
Create Date: 2025-05-23 18:25:35.321013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f07a1ae24f2'
down_revision = '9cb417623045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_location_flexible', sa.Boolean(), default=False))
        batch_op.add_column(sa.Column('place_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.drop_column('place_type')
        batch_op.drop_column('is_location_flexible')

    # ### end Alembic commands ###
