"""empty message

Revision ID: 50e9b50c6eb4
Revises: be0ae43dec93
Create Date: 2025-05-13 08:57:13.282360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50e9b50c6eb4'
down_revision = 'be0ae43dec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioritization_style', sa.Enum('important_first', 'quick_wins', 'balanced', name='prioritization_style'), nullable=False))
        batch_op.alter_column('travel_mode',
               existing_type=mysql.ENUM('driving', 'walking', 'transit'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('travel_mode',
               existing_type=mysql.ENUM('driving', 'walking', 'transit'),
               nullable=True)
        batch_op.drop_column('prioritization_style')

    # ### end Alembic commands ###
