"""transt mode modified

Revision ID: 531666e625e2
Revises: 1bbccb031710
Create Date: 2025-05-23 23:01:40.623344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '531666e625e2'
down_revision = '1bbccb031710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transit_modes', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=mysql.ENUM('car', 'bike', 'bus_train', 'walking', 'rideshare'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'transit_mode_options', ['mode'], ['mode'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transit_modes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mode',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('car', 'bike', 'bus_train', 'walking', 'rideshare'),
               existing_nullable=False)

    # ### end Alembic commands ###
