"""added transit mode in scheduled task

Revision ID: 55cbfa630359
Revises: seed_transit_modes
Create Date: 2025-05-26 01:28:27.327061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55cbfa630359'
down_revision = 'seed_transit_modes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transit_mode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_preferences_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('favorite_store_location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_store_location_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('user_preferences_ibfk_1'), 'locations', ['favorite_store_location_id'], ['location_id'], ondelete='SET NULL')

    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_column('transit_mode')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
