""" Added Status column

Revision ID: 9cb417623045
Revises: e4edfeb09d5b
Create Date: 2025-05-19 02:02:52.254427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cb417623045'
down_revision = 'e4edfeb09d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('not_completed', 'completed', name='task_status'), nullable=False))
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', mysql.JSON(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
