"""add UserPreference location fields

Revision ID: be0ae43dec93
Revises: 2b0b7ab58366
Create Date: 2025-05-10 03:43:29.197397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0ae43dec93'
down_revision = '2b0b7ab58366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_store_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['favorite_store_location_id'], ['location_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'locations', ['home_location_id'], ['location_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_store_location_id')
        batch_op.drop_column('home_location_id')

    # ### end Alembic commands ###
