"""updated Location table

Revision ID: e4edfeb09d5b
Revises: 1b7478657980
Create Date: 2025-05-16 00:55:45.658807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4edfeb09d5b'
down_revision = '1b7478657980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint('uq_location_coords', ['latitude', 'longitude'])
        batch_op.drop_constraint('locations_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('locations_ibfk_1', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_location_coords', type_='unique')
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
